services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'projetpedae3'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks: 
      - dev-network
      
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./back-end:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=projetpedae3
    restart: unless-stopped
    depends_on:
      - mysql
    networks: 
      - dev-network
    
  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - back-end
    networks: 
      - dev-network

volumes:
  db:

networks:
  dev-network: {}    